language: python
python:
  - "2.6"
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  - python setup.py install
script:
    - paver run_test
notifications:
  irc: "irc.freenode.org#irianas"
branches:
  only:
    - master
